name: Fly Deploy
on:
  push:
    branches:
      - main
      - staging
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy the-backend on Development OR Staging
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Deploy Testing/Dev
          if: github.ref == 'refs/heads/main'
          uses: superfly/flyctl-actions/setup-flyctl@master
          run: flyctl deploy -a the-backend --remote-only

        - name: Deploy Staging
          if: github.ref == 'refs/heads/staging'
          uses: superfly/flyctl-actions/setup-flyctl@master
          run: flyctl deploy -a staging-mintit-backend --remote-only