name: Prod - Fly Deploy
on:
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy to Production
      runs-on: ubuntu-latest
      steps:
        - name: Wait for approval
          uses: trstringer/manual-approval@v1
          with:
            secret: ${{ github.TOKEN }}
            approvers: abdur-docushield
            minimum-approvals: 1
            issue-title: "Deploying to Production"
          timeout-minutes: 5
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        #- run: flyctl deploy -a the-backend --remote-only